#!/usr/bin/env python3.5
#-*- coding:utf8 -*-

import string
test_value='MoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYdMoNiBYd'
print(len(test_value))
charArray = list(test_value)

re_value=list()


for index,char_target in enumerate(charArray):
    if(ord(char_target)>=65 and ord(char_target)<=90):
        re_value.append(index)


print(re_value)
